### ISSUE TITLE
SDLFacade deconstructor tries to free an invalid pointer

### ISSUE THREAD

**Issue by jorgdebont** [ThomasvLingen/Minor_vidya#18]
*** Error in `build/vidya': free(): invalid pointer: 0x00002afef3be6000 ***
See valgrind output (make memory_leaks)

**Comment by jorgdebont** [comment]
@Mfrielink refer to the PR number like this #23

**Comment by jorgdebont** [comment]
 Martijn_facadedeconstructor  $  make run
CC src/main.cpp

mkdir -p build/
LD build/vidya

Moving resources to build
cp -r res/ build/

build/vidya
Hello world
*** Error in `build/vidya': free(): invalid pointer: 0x00002b20902fd000 ***
make: *** [run] Aborted

**Comment by ThomasvLingen** [comment]
@jorgdebont Your log is fairly meaningless unless we have the exact code you tested with.

I, for example, don't experience an invalid free with my test.

[Here is my main](https://gist.github.com/ThomasvLingen/1ef45e04ed1d9581dff11b01bcd7a6a0)
