### ISSUE TITLE
SDL_Facade drawtext takes a coordinatedouble as position

### ISSUE THREAD

**Issue by jorgdebont** [ThomasvLingen/Minor_vidya#41]
coordinate double doesnt make any sense, and it is casted to a int in the function.
Please change this to a coordinateint

**Comment by ThomasvLingen** [comment]
There are more functions that needlessly take a double.
Another example is the new `draw_pixel_screen_buffer` function.

**Comment by Mfrielink** [comment]
Fixed in pr #56
