### ISSUE TITLE
Memoryleak in shared_ptr<GameLogic::Level>

### ISSUE THREAD

**Issue by Mfrielink** [ThomasvLingen/Minor_vidya#44]
De smartpointer naar level heeft waarschijnlijk een dubbele reference.

![level_memleak](https://cloud.githubusercontent.com/assets/7384876/20479619/2e717f14-afdf-11e6-85d2-7f10eb99d084.png)

**Comment by ThomasvLingen** [comment]
For future reference: [this](http://stackoverflow.com/questions/1826902/how-to-avoid-memory-leak-with-shared-ptr)

**Comment by ThomasvLingen** [comment]
Should be fixed with #70!
