### ISSUE TITLE
Unused parameter warnings are annoying.

### ISSUE THREAD

**Issue by ThomasvLingen** [ThomasvLingen/Minor_vidya#55]
Although in most cases they are correct, they're annoying in certain functions where usage of certain params just isn't needed. There is a simple solution to squelch this: cast the parameter to `void`

To do this in every single instance is stupid though, so I propose the following:

Qt has a very nice solution: an `UNUSED` macro. This way you **explicitly** mark the variable as unused, which is also clear from the macro name. We should implement something like this ourselves. Perhaps the macro can cast the parameter to void?

**Comment by Mfrielink** [comment]
Using Qt's solution for this problem seems fine by me, such macro would be easy to implement. Out with the unused-warnings!

**Comment by WoutervanGeel** [comment]
Is this really necessary at the moment? all unused-warnings in the dev are because of us defining a parameter which is not used now. Why bother implement this if we can just remove these parameters?

**Comment by joostvanrijsinge** [comment]
This solution only gives me one concern as this might make people loose track on a to-do. As with this everything seems done as you don't have warnings

**Comment by ThomasvLingen** [comment]
@WoutervanGeel 

Because in some cases, the parameter has to be there (think polymorphic functions like `update(int dt)`), but does not **have** to be used by every class that implements that function. Usage is optional there, therefore it would be neat if we could mark the param as unused in that specific implementation, and don't have to worry about warnings.

**Comment by ThomasvLingen** [comment]
@joostvanrijsinge 

It's true that an `UNUSED` macro can be abused just to squelch warnings, but that's not what it is intended for. It's intended to be used for **explicitly** ignoring a parameter. If a parameter is not used but should be used, the `UNUSED` macro should of course not be used there!

**Comment by ThomasvLingen** [comment]
I'd like to hear your thoughts after reading my response. Do you still disagree or are you persuaded?

**Comment by jorgdebont** [comment]
I agree
