### ISSUE TITLE
Knowledge share worldparser

### ISSUE THREAD

**Issue by joostvanrijsinge** [ThomasvLingen/Minor_vidya#97]
As I am the only one that has worked with the worldparser and tiled it might be a good Idea to have either one or two more people to know how it works. so for people that want to know when can I explain it to you.

**Comment by ThomasvLingen** [comment]
I agree that it would be nice if more people had knowledge of tiled and `.tmx` files beyond making maps.

Perhaps this is something we should discuss the next meeting (Ask @WoutervanGeel the meeting-overseer)!
